#!/usr/bin/env bash
# apply-layout.sh (*FR:Brunel*)
#
# Creates the hr-devs tmux layout: "full-review" (7 panes).
# Source: hr-platform/teams/hr-devs/docs/tmux-layouts.md
#
# Layout:
#   | lead   | marcus  | arvo      |
#   |        |---------------------|
#   |--------| tess    | sven      |
#   | finn   |---------------------|
#   |        | dag                 |
#
# Split tree:
#   Window (%0)
#   ├── split -h 30% → left (lead), right (R)
#   │   ├── split left -v 50% → lead, finn
#   │   └── split R -v 35% → marcus_row, RB
#   │       ├── split marcus_row -h 50% → marcus, arvo
#   │       └── split RB -v 50% → tess_row, dag
#   │           └── split tess_row -h 50% → tess, sven
#
# Uses absolute sizes (-l) not percentages (-p).
# Safe to call from any context: .bashrc, entrypoint, Claude Bash tool, external SSH.
# See container-deployment-runbook.md §17.
#
# Usage: apply-layout.sh [tmux-session]
#   Default session: hr-devs
#
# Output: writes /tmp/hr-devs-panes.env with PANE_* vars for spawn_member.sh.

set -e

TMUX_SESSION="${1:-hr-devs}"
WORK_DIR="/home/ai-teams/workspace/hr-platform/conversations"
PANE_ENV="/tmp/hr-devs-panes.env"

# Verify session exists
if ! tmux has-session -t "$TMUX_SESSION" 2>/dev/null; then
    echo "ERROR: tmux session '$TMUX_SESSION' not found. Create it first:" >&2
    echo "  tmux new-session -d -s $TMUX_SESSION" >&2
    exit 1
fi

# Get window dimensions (works without an attached client)
TOTAL_W=$(tmux display-message -t "$TMUX_SESSION" -p '#{window_width}')
TOTAL_H=$(tmux display-message -t "$TMUX_SESSION" -p '#{window_height}')

# Column widths (absolute)
LEFT_W=$((TOTAL_W * 30 / 100))
RIGHT_W=$((TOTAL_W - LEFT_W - 1))

# ── Pane 0: lead (top-left, initial pane) ────────────────────────────────────
PANE_LEAD=$(tmux list-panes -t "$TMUX_SESSION" -F '#{pane_id}' | head -1)

# ── Split right column (right 70%) ───────────────────────────────────────────
PANE_RIGHT=$(tmux split-window -t "$PANE_LEAD" -d -h -l "$RIGHT_W" -c "$WORK_DIR" -P -F '#{pane_id}' 'bash --norc -i')

# ── Split left column: finn below lead ───────────────────────────────────────
LEFT_BOTTOM_H=$((TOTAL_H / 2))
PANE_FINN=$(tmux split-window -t "$PANE_LEAD" -d -v -l "$LEFT_BOTTOM_H" -c "$WORK_DIR" -P -F '#{pane_id}' 'bash --norc -i')

# ── Split right column: marcus_row (top 35%) and RB (bottom 65%) ─────────────
RIGHT_H=$((TOTAL_H - 1))
MARCUS_ROW_H=$((RIGHT_H * 35 / 100))
RB_H=$((RIGHT_H - MARCUS_ROW_H - 1))
PANE_MARCUS="$PANE_RIGHT"
PANE_RB=$(tmux split-window -t "$PANE_RIGHT" -d -v -l "$RB_H" -c "$WORK_DIR" -P -F '#{pane_id}' 'bash --norc -i')

# ── Split marcus_row: marcus (left) + arvo (right) ──────────────────────────
ARVO_W=$((RIGHT_W / 2))
PANE_ARVO=$(tmux split-window -t "$PANE_MARCUS" -d -h -l "$ARVO_W" -c "$WORK_DIR" -P -F '#{pane_id}' 'bash --norc -i')

# ── Split RB: tess_row (top) + dag (bottom) ─────────────────────────────────
DAG_H=$((RB_H / 2))
PANE_TESS_ROW="$PANE_RB"
PANE_DAG=$(tmux split-window -t "$PANE_RB" -d -v -l "$DAG_H" -c "$WORK_DIR" -P -F '#{pane_id}' 'bash --norc -i')

# ── Split tess_row: tess (left) + sven (right) ──────────────────────────────
SVEN_W=$((RIGHT_W / 2))
PANE_TESS="$PANE_TESS_ROW"
PANE_SVEN=$(tmux split-window -t "$PANE_TESS_ROW" -d -h -l "$SVEN_W" -c "$WORK_DIR" -P -F '#{pane_id}' 'bash --norc -i')

# ── Label panes ──────────────────────────────────────────────────────────────
tmux select-pane -t "$PANE_LEAD"   -T "team-lead"
tmux select-pane -t "$PANE_FINN"   -T "finn"
tmux select-pane -t "$PANE_MARCUS" -T "marcus"
tmux select-pane -t "$PANE_ARVO"   -T "arvo"
tmux select-pane -t "$PANE_TESS"   -T "tess"
tmux select-pane -t "$PANE_SVEN"   -T "sven"
tmux select-pane -t "$PANE_DAG"    -T "dag"

tmux set-option -t "$TMUX_SESSION" pane-border-format " #{pane_title} "
tmux set-option -t "$TMUX_SESSION" pane-border-status top

# Focus on team-lead pane
tmux select-pane -t "$PANE_LEAD"

# ── Write pane env file ──────────────────────────────────────────────────────
cat > "$PANE_ENV" << EOF
# hr-devs tmux pane IDs (full-review layout) — source before spawn_member.sh
# Generated by apply-layout.sh at $(date)
export PANE_LEAD=${PANE_LEAD}
export PANE_FINN=${PANE_FINN}
export PANE_MARCUS=${PANE_MARCUS}
export PANE_ARVO=${PANE_ARVO}
export PANE_TESS=${PANE_TESS}
export PANE_SVEN=${PANE_SVEN}
export PANE_DAG=${PANE_DAG}
EOF

echo "Layout 'full-review' applied to session: $TMUX_SESSION"
echo "Pane IDs written to: $PANE_ENV"
echo ""
echo "  team-lead: $PANE_LEAD"
echo "  finn:      $PANE_FINN"
echo "  marcus:    $PANE_MARCUS"
echo "  arvo:      $PANE_ARVO"
echo "  tess:      $PANE_TESS"
echo "  sven:      $PANE_SVEN"
echo "  dag:       $PANE_DAG"
echo ""
echo "Spawn agents with:"
echo "  source $PANE_ENV"
echo "  spawn_member.sh --target-pane \$PANE_FINN    finn    $TMUX_SESSION"
echo "  spawn_member.sh --target-pane \$PANE_MARCUS  marcus  $TMUX_SESSION"
echo "  spawn_member.sh --target-pane \$PANE_ARVO    arvo    $TMUX_SESSION"
echo "  spawn_member.sh --target-pane \$PANE_TESS    tess    $TMUX_SESSION"
echo "  spawn_member.sh --target-pane \$PANE_SVEN    sven    $TMUX_SESSION"
echo "  spawn_member.sh --target-pane \$PANE_DAG     dag     $TMUX_SESSION"
